//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qcsolver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConstructionSite()
        {
            this.AssignedWorkers = new HashSet<AssignedWorker>();
            this.Schedules = new HashSet<Schedule>();
            this.Timestamps = new HashSet<Timestamp>();
        }
    
        public int constructionSiteId { get; set; }
        public string address { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string city { get; set; }
        public int company { get; set; }
        public int country { get; set; }
        public int province { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedWorker> AssignedWorkers { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Province Province1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timestamp> Timestamps { get; set; }
    }
}
