//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qcsolver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public int licenseId { get; set; }
        public string licenseName { get; set; }
        public System.DateTime dateIssued { get; set; }
        public Nullable<System.DateTime> expirationDate { get; set; }
        public string fileLocation { get; set; }
        public int person { get; set; }
    
        public virtual Person Person1 { get; set; }
    }
}
