//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qcsolver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int scheduleId { get; set; }
        public System.DateTime startDateTime { get; set; }
        public int duration { get; set; }
        public int person { get; set; }
        public int constructionSite { get; set; }
    
        public virtual ConstructionSite ConstructionSite1 { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
