//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qcsolver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail
    {
        public int detailId { get; set; }
        public string details { get; set; }
        public int assigned { get; set; }
    
        public virtual AssignedWorker AssignedWorker { get; set; }
    }
}
