//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qcsolver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timestamp
    {
        public int timestampId { get; set; }
        public System.DateTime timeIn { get; set; }
        public Nullable<System.DateTime> timeOut { get; set; }
        public int person { get; set; }
        public int constructionSite { get; set; }
    
        public virtual ConstructionSite ConstructionSite1 { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
